In [2]:
import torch
label=torch.tensor([[0,0,1,0,1,2],[0,1,1,1,2,0]])
one_label=torch.nn.functional.one_hot(label,num_classes=3)
one_label

tensor([[[1, 0, 0],
         [1, 0, 0],
         [0, 1, 0],
         [1, 0, 0],
         [0, 1, 0],
         [0, 0, 1]],

        [[1, 0, 0],
         [0, 1, 0],
         [0, 1, 0],
         [0, 1, 0],
         [0, 0, 1],
         [1, 0, 0]]])

In [3]:
Nlabel=(torch.ones(3)-one_label)/3*2

In [10]:
Nlabel

tensor([[[0.0000, 0.6667, 0.6667],
         [0.0000, 0.6667, 0.6667],
         [0.6667, 0.0000, 0.6667],
         [0.0000, 0.6667, 0.6667],
         [0.6667, 0.0000, 0.6667],
         [0.6667, 0.6667, 0.0000]],

        [[0.0000, 0.6667, 0.6667],
         [0.6667, 0.0000, 0.6667],
         [0.6667, 0.0000, 0.6667],
         [0.6667, 0.0000, 0.6667],
         [0.6667, 0.6667, 0.0000],
         [0.0000, 0.6667, 0.6667]]])

In [5]:
pre=torch.rand((3,4))
pre

tensor([[0.2465, 0.5318, 0.2950, 0.3883],
        [0.8325, 0.4854, 0.4569, 0.9656],
        [0.0714, 0.6405, 0.9809, 0.8309]])

In [15]:
mask=torch.ones(3)
mask

tensor([1., 1., 1.])

In [16]:
mask[1]=0

In [17]:
pre_mask=pre*mask.unsqueeze(1)

In [18]:
pre,pre_mask

(tensor([[0.2465, 0.5318, 0.2950, 0.3883],
         [0.8325, 0.4854, 0.4569, 0.9656],
         [0.0714, 0.6405, 0.9809, 0.8309]]),
 tensor([[0.2465, 0.5318, 0.2950, 0.3883],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0714, 0.6405, 0.9809, 0.8309]]))